# Generated by Django 6.1.1 on 2026-09-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_product_seller_product_store_and_more'),
        ('stores', '0002_alter_store_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='فروشگاه'),
        ),
    ]
